# Lecture 2
We are now starting ML stuff, yay

For vectorization:
`ndarray`

In [2]:
import numpy as np

v = np.array([1, 2, 3])

In [3]:
v

array([1, 2, 3])

In [4]:
type(v)

numpy.ndarray

In [5]:
v.ndim

1

In [6]:
v.size

3

In [7]:
v.dtype

dtype('int64')

In [8]:
v.data

Now we can create a matrix

In [9]:
m = np.array(
    [[1,2,3],
    [4,5,6]]
)

In [10]:
m

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
m.shape

(2, 3)

In [12]:
m.reshape
m

array([[1, 2, 3],
       [4, 5, 6]])

## Tensors
This is how we do Tensors, or multidemisionsal matrices

In [13]:
t = np.array(
    [[[1,2,3],
      [4,5,6]],
      
      [[7,8,9],
       [10,11,12]]]
)

In [14]:
t.ndim

3

In [15]:
t.shape

(2, 2, 3)

In [18]:
e = np.eye(5).T #nice
e

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
d = np.diag([1, 50, 8, 90])
d

array([[ 1,  0,  0,  0],
       [ 0, 50,  0,  0],
       [ 0,  0,  8,  0],
       [ 0,  0,  0, 90]])

In [21]:
e = np.empty((2,3))
e

array([[4.67333224e-310, 0.00000000e+000, 6.93577660e-310],
       [6.93577676e-310, 6.93578620e-310, 6.93577660e-310]])

Creating uniformity in random sets

In [23]:
import time
t = time.time()
print(t)
np.random.seed(int(t))
ra = np.random.rand(3,4)
ra

1694643065.4452841


array([[0.65433722, 0.12435376, 0.57545585, 0.54647138],
       [0.90337984, 0.55384566, 0.67721185, 0.89392918],
       [0.35621606, 0.98799217, 0.28274497, 0.98924436]])

In [24]:
ra = np.random.randint(5,10,(3,4))
ra

array([[5, 8, 5, 8],
       [6, 5, 8, 5],
       [7, 8, 6, 5]])

In [25]:
nice = np.arange(10, 20, 0.5)
nice

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. ,
       15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5])

In [26]:
nice.shape

(20,)

Creating a linspace is the same in MATLAB (ew)

In [27]:
lin = np.linspace(-10, 10, 20)
lin

array([-10.        ,  -8.94736842,  -7.89473684,  -6.84210526,
        -5.78947368,  -4.73684211,  -3.68421053,  -2.63157895,
        -1.57894737,  -0.52631579,   0.52631579,   1.57894737,
         2.63157895,   3.68421053,   4.73684211,   5.78947368,
         6.84210526,   7.89473684,   8.94736842,  10.        ])

In [29]:
log = np.logspace(-100, 100)
log

array([1.00000000e-100, 1.20679264e-096, 1.45634848e-092, 1.75751062e-088,
       2.12095089e-084, 2.55954792e-080, 3.08884360e-076, 3.72759372e-072,
       4.49843267e-068, 5.42867544e-064, 6.55128557e-060, 7.90604321e-056,
       9.54095476e-052, 1.15139540e-047, 1.38949549e-043, 1.67683294e-039,
       2.02358965e-035, 2.44205309e-031, 2.94705170e-027, 3.55648031e-023,
       4.29193426e-019, 5.17947468e-015, 6.25055193e-011, 7.54312006e-007,
       9.10298178e-003, 1.09854114e+002, 1.32571137e+006, 1.59985872e+010,
       1.93069773e+014, 2.32995181e+018, 2.81176870e+022, 3.39322177e+026,
       4.09491506e+030, 4.94171336e+034, 5.96362332e+038, 7.19685673e+042,
       8.68511374e+046, 1.04811313e+051, 1.26485522e+055, 1.52641797e+059,
       1.84206997e+063, 2.22299648e+067, 2.68269580e+071, 3.23745754e+075,
       3.90693994e+079, 4.71486636e+083, 5.68986603e+087, 6.86648845e+091,
       8.28642773e+095, 1.00000000e+100])

In [32]:
np_x = np.random.rand(100_000_000).reshape(1000, -1)
list_x = list(np_x)

In [33]:
type(list_x)

list

In [34]:
result = np.zeros(np_x.shape)

for i, x in enumerate(np_x):
    result[i] = x ** 3

Don't use lists, bottom line

In [39]:
a = np.ones([2,2])
a
b = np.array([[2,3],
              [3,4]])
b

array([[2, 3],
       [3, 4]])

In [40]:
a.dot(b)

array([[5., 7.],
       [5., 7.]])

In [41]:
np.dot(a,b)

array([[5., 7.],
       [5., 7.]])

In [42]:
a < 1

array([[False, False],
       [False, False]])

In [45]:
a.sum(axis = -2)

array([2., 2.])